#!/bin/bash
#*************************************************************************
#* tools/delete
#*
#* Copyright (c) 2012 Michael D Henderson, all rights reserved
#*
## This file is part of wraithe (http://github.com/quoha/wraithe).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##************************************************************************

retVal=0
while [ -n "${1}" ]
do
  # if parm is a file, try to delete it
  [ -f "${1}" ] && rm -f "${1}"

  # if it still exists then report an error
  if [ -e "${1}" ]
  then
    echo "error: unable to delete '${1}'"
    retVal=2
  fi
  shift
done
exit $retVal
