#!/bin/bash
##************************************************************************
## wraithe/tools/manifest
##
## Copyright (c) 2012 Michael D Henderson, all rights reserved
##
## This file is part of wraithe
##************************************************************************

while [ -n "${1}" ]
do
  [ "${1}" == all  -o "${1}" == --all  ] && find .   -type f
  [ "${1}" == dir  -o "${1}" == --dir  ] && find src -type d
  [ "${1}" == file -o "${1}" == --file ] && find src -type f
  shift
done | grep -v '.git' | sed -e 's/^\.$//' -e 's/^\.\///' -e '/^$/d' | sort -u

exit 0
